name: Deploy API

on:
  pull_request:
#    types:
#      - closed
    branches:
#      - master

jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/api .
          docker push ${{secrets.DOCKER_USERNAME}}/api:latest