services:
  postgres:
    image: postgres:latest
    container_name: postgres_web_test
    ports:
      - "6500:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env

  rusty:
    build: .
    ports:
      - "8080:8080"
    env_file: .env

volumes:
  progresDB: