services:
  postgres:
    image: postgres:latest
    container_name: postgres_web_test
    ports:
      - "6500:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    env_file:
      - ./.env
    restart: unless-stopped

volumes:
  progresDB:
  rabbitmq_data:
  rabbitmq_log:
