name: Docker Image CD

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: "eu-west-1"
          role-session-name: Service_CD_GitHub_to_AWS_via_FederatedOIDC

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Check install
        run: cosign version

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.2.0
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create New API Version
        run: |
          aws elasticbeanstalk create-application-version --application-name home-loans-service --version-label "deploy-${{ github.sha }}" --description "commit-sha-${{ github.sha }}"
#          aws elasticbeanstalk update-environment --application-name home-loans-service --version-label ${{ github.sha }}
#--source-bundle S3Bucket="${{ inputs.account-id  }}-deploy-bucket",S3Key="deploy_package.zip"
#      - name: upload to EBS
#        id: upload-ebs
#        uses: einaregilsson/beanstalk-deploy@v22
#        with:
#          application_name: home-loans-service-env
#          environment_name: home-loans-service-env
#          version_label: "deploy-${{ github.sha }}"
#          region: us-west-2
#          aws_access_key: ${{ secrets.ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}