name: Docker Image CI

on:
  push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3.3.0
      - uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6.2.0
        with:
          push: true
          #          tags: ghcr.io/${{ github.repository_owner }}/home-loans-backend:${{ github.run_id }}
          tags: ghcr.io/${{ github.repository_owner }}/home-loans-backend:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max