name: Docker Image CI

on:
  push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v1
      - uses: docker/buitd-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max